name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # This triggers the workflow on every push to the main branch
  pull_request:
    branches:
      - main  # This triggers the workflow on PRs to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Use your GitHub secret for DockerHub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Use your GitHub secret for DockerHub password

      # Build and push the Docker images
      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build  # Build the Docker images
          docker-compose -f docker-compose.yml up -d  # Start the containers in detached mode

      # Optional: Run tests (if you have tests configured)
      - name: Run tests
        run: |
          # Example: Run your tests (this is just a placeholder; modify based on your test setup)
          npm test  # Replace with your test command
